baseurl = "http://www.tenfourty.com/"
languageCode = "en-us"
title = "tenfourty.com"
disqusShortname = "tenfourty"
GoogleAnalytics = "UA-70241202-1"
theme = "herring-cove"

[permalinks]
  posts = ":year/:month/:day/:title/"

[params]
  ProfilePicture = "/ProfilePicture.jpg"
  enableLandingPage = false
  landingPageRedirectUrl = "/about"
  AuthorName = "Jeremy Brown"
#  twitter = "https://twitter.com/tenfourty"
#  linkedin = "https://www.linkedin.com/in/tenfourty"
#  facebook = "https://facebook.com/tenfourty"
#  github = "https://github.com/tenfourty"
  [params.links]
    About = "about/"
#    Posts = "/"
#    Tags = "/tags/"
