source = "site/"
contentdir = "site/content"
dataDir = "site/data"
layoutDir = "site/layouts"
themesDir = "site/themes"
publishDir = "site/public"
staticDir = "site/static"
i18nDir = "site/i18n"
baseurl = "https://www.tenfourty.com"
languageCode = "en-us"
title = "tenfourty.com"
disqusShortname = "tenfourty"
GoogleAnalytics = "UA-70241202-1"
theme = "hyde-x"
paginate = "20"

[author]
  name = "Jeremy Brown"

[permalinks]
  post = "/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
  # If false display full article contents in blog index.
  # Otherwise show description and 'read on' link to individual blog post page.
  # Default (if omitted) is true.
  truncate = true

  # Used when a given page doesn't set its own.
  defaultDescription = "This is a page on www.tenfourty.com"
  defaultKeywords = "tenfourty,jeremy brown,jeremy"

  # Hide estimated reading time for posts.
  # Default (if omitted) is false.
  hideReadingTime = false

  # Changes sidebar background and link/accent colours.
  # See below for more colour options.
  # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
  theme = "theme-base-0c"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight = "solarized_dark"

  # Optional additional custom CSS file URL, will override other styles.
  customCSS = ""

  # Displays under the author name in the sidebar, keep it short.
  # You can use markdown here.
  tagline = "Adventurer and Geek"

  # Text for the top menu link, which goes the root URL for the site.
  # Default (if omitted) is "Blog".
  home = "Home"

  # Metadata used to drive integrations.
  googleAnalytics = "UA-70241202-1"
  gravatarHash = "677b94ebd9f74163b013a821bd34b97a"

  # Sidebar social links, these must be full URLs.
  github = "https://github.com/tenfourty"
  bitbucket = ""
  stackOverflow = ""
  linkedin = "https://www.linkedin.com/in/tenfourty"
  googleplus = ""
  facebook = "https://facebook.com/tenfourty"
  twitter = "https://twitter.com/tenfourty"
  youtube = ""

  # Other social-like sidebar links
  rss = true  # switch to true to enable RSS icon link
#  flattr = "tenfourty"  # populate with your flattr uid

#  profilepicture = "/ProfilePicture.jpg"
#  enablelandingpage = false
#  landingpageredirecturl = "/about"
#  authorname = "Jeremy Brown"
#  copyright = "2016"
#  twitter = "https://twitter.com/tenfourty"
#  linkedin = "https://www.linkedin.com/in/tenfourty"
#  facebook = "https://facebook.com/tenfourty"
#  github = "https://github.com/tenfourty"
#  [params.links]
#    About = "/about/"
#    PetStore = "/petstore/"
#    Posts = "/"
#    Tags = "/tags/"
