baseurl = "http://www.tenfourty.com"
languageCode = "en-us"
title = "tenfourty.com"
disqusShortname = "tenfourty"
theme = "herring-cove"

[params]
  ProfilePicture = "/tenfourty_1337687145_98.jpg"
  enableLandingPage = false
  landingPageRedirectUrl = "/about"
  AuthorName = "Jeremy Brown"
#  twitter = "https://twitter.com/tenfourty"
#  linkedin = "https://www.linkedin.com/in/tenfourty"
#  facebook = "https://facebook.com/tenfourty"
#  github = "https://github.com/tenfourty"
  [params.links]
    About = "/about/"
    Posts = "/"
#    Tags = "/tags/"
