---
new_page_extension: md
auto_deploy: false
admin_path: "/site/static/admin/"
webhook_url: 
sections:
- type: document
  path: site/content/_index.md
  label: index
  match: "**/*"
upload_dir: site/static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.20.7
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public --source site --config site/config.toml
version: '0.17'
